=== churcho/ehealth.api/apps/core/specs/json_schemas/legal_entity/v2/legal_entity_create_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "date": {
      "type": "string",
      "pattern": "^(\\d{4}(?!\\d{2}\\b))((-)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6]))))$"
    },
    "name": {
      "type": "string",
      "pattern": "^(?!.*[ЫЪЭЁыъэё@%&$^#])[a-zA-ZА-ЯҐЇІЄа-яґїіє0-9№\\\"!\\^\\*)\\]\\[(._-].*$"
    },
    "person_name": {
      "type": "string",
      "pattern": "^(?!.*[ЫЪЭЁыъэё@%&$^#])[А-ЯҐЇІЄа-яґїіє\\'\\- ]+$"
    },
    "gender": {
      "type": "string",
      "description": "Dictionary: GENDER"
    },
    "phone": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Dictionary: PHONE_TYPE"
        },
        "number": {
          "type": "string",
          "pattern": "^\\+38[0-9]{10}$"
        }
      },
      "required": [
        "type",
        "number"
      ],
      "additionalProperties": false
    },
    "document": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Dictionary: DOCUMENT_TYPE"
        },
        "number": {
          "type": "string",
          "minLength": 1
        },
        "issued_by": {
          "type": "string",
          "minLength": 1
        },
        "issued_at": {
          "type": "string",
          "format": "date"
        }
      },
      "required": [
        "type",
        "number"
      ],
      "additionalProperties": false
    },
    "address": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "RESIDENCE"
          ]
        },
        "country": {
          "type": "string"
        },
        "area": {
          "$ref": "#/definitions/name"
        },
        "region": {
          "$ref": "#/definitions/name"
        },
        "settlement": {
          "$ref": "#/definitions/name"
        },
        "settlement_type": {
          "type": "string",
          "description": "settlement type Dictionary: SETTLEMENT_TYPE"
        },
        "settlement_id": {
          "type": "string",
          "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
        },
        "street_type": {
          "type": "string",
          "description": "street type Dictionary: STREET_TYPE"
        },
        "street": {
          "$ref": "#/definitions/name"
        },
        "building": {
          "type": "string",
          "pattern": "^[1-9]((?![ЫЪЭЁыъэё])()([А-ЯҐЇІЄа-яґїіє \\/\\'\\-0-9])){0,20}$"
        },
        "apartment": {
          "type": "string"
        },
        "zip": {
          "type": "string",
          "pattern": "^[0-9]{5}$"
        }
      },
      "required": [
        "type",
        "country",
        "area",
        "settlement",
        "settlement_type",
        "settlement_id"
      ],
      "additionalProperties": false
    },
    "archive": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "#/definitions/date"
        },
        "place": {
          "$ref": "#/definitions/name"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "edrpou": {
      "type": "string",
      "pattern": "^[0-9]{8,10}|[0-9]{9,10}$"
    },
    "type": {
      "type": "string",
      "description": "Dictionary: LEGAL_ENTITY_TYPE_V2"
    },
    "residence_address": {
      "$ref": "#/definitions/address"
    },
    "phones": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/phone"
      },
      "minItems": 1
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "website": {
      "type": "string",
      "pattern": "^(http:\/\/|https:\/\/)?([a-z0-9][a-z0-9\\-]*\\.)+[a-z0-9][a-z0-9\\-]*$"
    },
    "receiver_funds_code": {
      "type": "string",
      "pattern": "^[0-9]+$"
    },
    "beneficiary": {
      "type": "string",
      "pattern": "^(?!.*[ЫЪЭЁыъэё@%&$^#])[А-ЯҐЇІЄа-яґїіє\\'\\- ]+$"
    },
    "owner": {
      "type": "object",
      "properties": {
        "first_name": {
          "$ref": "#/definitions/person_name"
        },
        "last_name": {
          "$ref": "#/definitions/person_name"
        },
        "second_name": {
          "type": [
            "string",
            "null"
          ],
          "pattern": "^(?!.*[ЫЪЭЁыъэё@%&$^#])[А-ЯҐЇІЄа-яґїіє\\'\\- ]+$"
        },
        "position": {
          "type": "string",
          "description": "Dictionary: POSITION"
        },
        "tax_id": {
          "type": "string",
          "pattern": "^([0-9]{9,10}|[А-ЯЁЇIЄҐ]{2}\\d{6})$"
        },
        "birth_date": {
          "$ref": "#/definitions/date"
        },
        "gender": {
          "$ref": "#/definitions/gender"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "documents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/document"
          },
          "minItems": 1
        },
        "phones": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/phone"
          },
          "minItems": 1
        }
      },
      "required": [
        "first_name",
        "last_name",
        "position",
        "tax_id",
        "birth_date",
        "gender",
        "documents",
        "email"
      ],
      "additionalProperties": false
    },
    "accreditation": {
      "type": "object",
      "properties": {
        "category": {
          "type": "string",
          "description": "Dictionary: ACCREDITATION_CATEGORY"
        },
        "issued_date": {
          "$ref": "#/definitions/date"
        },
        "expiry_date": {
          "$ref": "#/definitions/date"
        },
        "order_no": {
          "$ref": "#/definitions/name",
          "description": "номер наказу МОЗ"
        },
        "order_date": {
          "$ref": "#/definitions/date"
        }
      },
      "required": [
        "category",
        "order_no"
      ],
      "additionalProperties": false
    },
    "license": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$"
        },
        "type": {
          "type": "string",
          "description": "Dictionary: LICENSE_TYPE"
        },
        "license_number": {
          "$ref": "#/definitions/name"
        },
        "issued_by": {
          "$ref": "#/definitions/name"
        },
        "issued_date": {
          "$ref": "#/definitions/date"
        },
        "expiry_date": {
          "$ref": "#/definitions/date"
        },
        "active_from_date": {
          "$ref": "#/definitions/date"
        },
        "what_licensed": {
          "$ref": "#/definitions/name"
        },
        "order_no": {
          "$ref": "#/definitions/name",
          "description": "номер наказу"
        }
      },
      "additionalProperties": false
    },
    "status": {
      "type": "string",
      "enum": [
        "ACTIVE",
        "CLOSED"
      ]
    },
    "archive": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/archive"
      }
    },
    "security": {
      "type": "object",
      "properties": {
        "redirect_uri": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https):\/\/.+"
        }
      },
      "required": [
        "redirect_uri"
      ]
    },
    "public_offer": {
      "type": "object",
      "properties": {
        "consent": {
          "type": "boolean",
          "enum": [
            true
          ]
        },
        "consent_text": {
          "type": "string"
        }
      },
      "required": [
        "consent",
        "consent_text"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "edrpou",
    "type",
    "residence_address",
    "phones",
    "email",
    "owner",
    "security",
    "public_offer"
  ],
  "additionalProperties": false
}

=== churcho/ehealth.api/apps/core/test/data/v2/legal_entity.json
{
  "edrpou": "37367387",
  "type": "PRIMARY_CARE",
  "residence_address": {
    "type": "RESIDENCE",
    "country": "UA",
    "area": "Житомирська",
    "region": "Бердичівський",
    "settlement": "Київ",
    "settlement_type": "CITY",
    "settlement_id": "f2d556b4-86d5-4afe-87b8-3908ad947106",
    "street": "вул. Ніжинська",
    "street_type": "STREET",
    "building": "15-В",
    "apartment": "23",
    "zip": "02090"
  },
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "email@example.com",
  "owner": {
    "first_name": "Петро",
    "last_name": "Іванов",
    "second_name": "Миколайович",
    "position": "P1",
    "tax_id": "3067305998",
    "birth_date": "1991-08-19",
    "gender": "MALE",
    "email": "email@example.com",
    "documents": [
      {
        "type": "PASSPORT",
        "number": "120518"
      }
    ],
    "phones": [
      {
        "type": "MOBILE",
        "number": "+380503410870"
      }
    ]
  },
  "accreditation": {
    "category": "ДРУГА",
    "issued_date": "1991-08-19",
    "expiry_date": "1991-08-19",
    "order_no": "fd123443",
    "order_date": "1991-08-19"
  },
  "license": {
    "type": "MSP",
    "license_number": "fd123443",
    "issued_by": "Кваліфікацйна комісія",
    "issued_date": "1991-08-19",
    "expiry_date": "2991-08-19",
    "active_from_date": "1991-08-19",
    "order_no": "fd123443",
    "what_licensed": "збут наркотичних засобів"
  },
  "security": {
    "redirect_uri": "https://example.com/redirect_uri"
  },
  "public_offer": {
    "consent": true,
    "consent_text": "Consent text"
  },
  "archive": [
    {
      "date": "2012-12-29",
      "place": "Житомир вул. Малярів, буд. 211, корп. 2, оф. 1"
    }
  ],
  "receiver_funds_code": "01855",
  "website": "https://boris.example.com",
  "beneficiary": "Лев Томас"
}
